{
  "name": "Deploy via git ftp",
  "on": {
    "push": {
      "branches": [
        "master"
      ]
    }
  },
  "jobs": {
    "deploy": {
      "name": "Deploy",
      "runs-on": "ubuntu-latest",
      "steps": [
        {
          "uses": "actions/checkout@v1"
        },
        {
          "name": "git-ftp push",
          "uses": "sebastianpopp/git-ftp-action@releases/v3",
          "with": {
            "url": "${{ secrets.FTP_URL }}",
            "user": "${{ secrets.FTP_USERNAME }}",
            "password": "${{ secrets.FTP_PASSWORD }}"
          }
        }
      ]
    }
  }
}